from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 880)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/gaming.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonFollowStyle)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1281, 861))
        self.stackedWidget.setObjectName("stackedWidget")
        self.computers = QtWidgets.QWidget()
        self.computers.setObjectName("computers")
        self.third_computer_button = QtWidgets.QPushButton(parent=self.computers)
        self.third_computer_button.setGeometry(QtCore.QRect(930, 40, 311, 291))
        self.third_computer_button.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.third_computer_button.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.third_computer_button.setText("")
        self.third_computer_button.setIcon(icon)
        self.third_computer_button.setIconSize(QtCore.QSize(351, 291))
        self.third_computer_button.setObjectName("third_computer_button")
        self.third_computer_label = QtWidgets.QLabel(parent=self.computers)
        self.third_computer_label.setGeometry(QtCore.QRect(930, 350, 161, 20))
        self.third_computer_label.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.third_computer_label.setObjectName("third_computer_label")
        self.fifth_computer_button = QtWidgets.QPushButton(parent=self.computers)
        self.fifth_computer_button.setGeometry(QtCore.QRect(490, 450, 311, 291))
        self.fifth_computer_button.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.fifth_computer_button.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.fifth_computer_button.setText("")
        self.fifth_computer_button.setIcon(icon)
        self.fifth_computer_button.setIconSize(QtCore.QSize(351, 291))
        self.fifth_computer_button.setObjectName("fifth_computer_button")
        self.first_computer_button = QtWidgets.QPushButton(parent=self.computers)
        self.first_computer_button.setGeometry(QtCore.QRect(50, 40, 311, 291))
        self.first_computer_button.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.first_computer_button.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.first_computer_button.setText("")
        self.first_computer_button.setIcon(icon)
        self.first_computer_button.setIconSize(QtCore.QSize(351, 291))
        self.first_computer_button.setObjectName("first_computer_button")
        self.fifth_computer_label = QtWidgets.QLabel(parent=self.computers)
        self.fifth_computer_label.setGeometry(QtCore.QRect(490, 760, 161, 20))
        self.fifth_computer_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.fifth_computer_label.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.fifth_computer_label.setObjectName("fifth_computer_label")
        self.sixth_computer_button = QtWidgets.QPushButton(parent=self.computers)
        self.sixth_computer_button.setGeometry(QtCore.QRect(930, 450, 311, 291))
        self.sixth_computer_button.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.sixth_computer_button.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.sixth_computer_button.setText("")
        self.sixth_computer_button.setIcon(icon)
        self.sixth_computer_button.setIconSize(QtCore.QSize(351, 291))
        self.sixth_computer_button.setObjectName("sixth_computer_button")
        self.second_computer_button = QtWidgets.QPushButton(parent=self.computers)
        self.second_computer_button.setGeometry(QtCore.QRect(490, 40, 311, 291))
        self.second_computer_button.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.second_computer_button.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.second_computer_button.setText("")
        self.second_computer_button.setIcon(icon)
        self.second_computer_button.setIconSize(QtCore.QSize(351, 291))
        self.second_computer_button.setObjectName("second_computer_button")
        self.fourth_computer_button = QtWidgets.QPushButton(parent=self.computers)
        self.fourth_computer_button.setGeometry(QtCore.QRect(40, 450, 311, 291))
        self.fourth_computer_button.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.fourth_computer_button.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.fourth_computer_button.setText("")
        self.fourth_computer_button.setIcon(icon)
        self.fourth_computer_button.setIconSize(QtCore.QSize(351, 291))
        self.fourth_computer_button.setObjectName("fourth_computer_button")
        self.second_computer_label = QtWidgets.QLabel(parent=self.computers)
        self.second_computer_label.setGeometry(QtCore.QRect(490, 350, 161, 20))
        self.second_computer_label.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.second_computer_label.setObjectName("second_computer_label")
        self.fourth_computer_label = QtWidgets.QLabel(parent=self.computers)
        self.fourth_computer_label.setGeometry(QtCore.QRect(40, 760, 161, 20))
        self.fourth_computer_label.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.fourth_computer_label.setObjectName("fourth_computer_label")
        self.first_computer_label = QtWidgets.QLabel(parent=self.computers)
        self.first_computer_label.setGeometry(QtCore.QRect(50, 350, 161, 20))
        self.first_computer_label.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.first_computer_label.setObjectName("first_computer_label")
        self.sixth_computer_label = QtWidgets.QLabel(parent=self.computers)
        self.sixth_computer_label.setGeometry(QtCore.QRect(930, 760, 161, 20))
        self.sixth_computer_label.setStyleSheet("background-color: rgba(255, 255, 255, 0); font-weight: bold;")
        self.sixth_computer_label.setObjectName("sixth_computer_label")
        self.stackedWidget.addWidget(self.computers)
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.reservations_calendar = QtWidgets.QCalendarWidget(parent=self.settings)
        self.reservations_calendar.setGeometry(QtCore.QRect(780, 30, 481, 321))
        self.reservations_calendar.setObjectName("reservations_calendar")
        self.reservations_list = QtWidgets.QListWidget(parent=self.settings)
        self.reservations_list.setGeometry(QtCore.QRect(780, 390, 481, 421))
        self.reservations_list.setObjectName("reservations_list")
        self.remove_five_minutes_button = QtWidgets.QPushButton(parent=self.settings)
        self.remove_five_minutes_button.setGeometry(QtCore.QRect(530, 100, 211, 191))
        self.remove_five_minutes_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.remove_five_minutes_button.setObjectName("remove_five_minutes_button")
        self.start_session_button = QtWidgets.QPushButton(parent=self.settings)
        self.start_session_button.setGeometry(QtCore.QRect(30, 100, 211, 191))
        self.start_session_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.start_session_button.setObjectName("start_session_button")
        self.add_five_minutes_button = QtWidgets.QPushButton(parent=self.settings)
        self.add_five_minutes_button.setGeometry(QtCore.QRect(280, 100, 211, 191))
        self.add_five_minutes_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.add_five_minutes_button.setObjectName("add_five_minutes_button")
        self.remove_one_warning_button = QtWidgets.QPushButton(parent=self.settings)
        self.remove_one_warning_button.setGeometry(QtCore.QRect(530, 330, 211, 191))
        self.remove_one_warning_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.remove_one_warning_button.setObjectName("remove_one_warning_button")
        self.send_warning_button = QtWidgets.QPushButton(parent=self.settings)
        self.send_warning_button.setGeometry(QtCore.QRect(280, 330, 211, 191))
        self.send_warning_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.send_warning_button.setObjectName("send_warning_button")
        self.block_session_button = QtWidgets.QPushButton(parent=self.settings)
        self.block_session_button.setGeometry(QtCore.QRect(30, 330, 211, 191))
        self.block_session_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.block_session_button.setObjectName("block_session_button")

        self.remove_reservation_button = QtWidgets.QPushButton(parent=self.settings)
        self.remove_reservation_button.setGeometry(QtCore.QRect(530, 560, 211, 191))
        self.remove_reservation_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.remove_reservation_button.setObjectName("remove_reservation_button")
        self.add_reservation_button = QtWidgets.QPushButton(parent=self.settings)
        self.add_reservation_button.setGeometry(QtCore.QRect(280, 560, 211, 191))
        self.add_reservation_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.add_reservation_button.setObjectName("add_reservation_button")
        self.back_button = QtWidgets.QPushButton(parent=self.settings)
        self.back_button.setGeometry(QtCore.QRect(30, 560, 211, 191))
        self.back_button.setStyleSheet("background-color: rgba(255, 255, 255, 125); font-weight: bold;")
        self.back_button.setObjectName("back_button")
        self.label = QtWidgets.QLabel(parent=self.settings)
        self.label.setGeometry(QtCore.QRect(30, 50, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.settings)
        self.label_2.setGeometry(QtCore.QRect(140, 50, 101, 16))
        self.label_2.setStyleSheet(" font-weight: bold;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.settings)
        self.label_3.setGeometry(QtCore.QRect(300, 50, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.settings)
        self.label_4.setGeometry(QtCore.QRect(460, 50, 47, 16))
        self.label_4.setStyleSheet(" font-weight: bold;")
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.settings)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.main_menu = QtWidgets.QMenu(parent=self.menubar)
        self.main_menu.setObjectName("main_menu")
        self.themes = QtWidgets.QMenu(parent=self.main_menu)
        self.themes.setObjectName("themes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtGui.QAction(parent=MainWindow)
        self.action_2.setObjectName("action_2")
        self.white_theme_button = QtGui.QAction(parent=MainWindow)
        self.white_theme_button.setObjectName("white_theme_button")
        self.black_theme_button = QtGui.QAction(parent=MainWindow)
        self.black_theme_button.setObjectName("black_theme_button")
        self.themes.addAction(self.white_theme_button)
        self.themes.addAction(self.black_theme_button)
        self.main_menu.addAction(self.themes.menuAction())
        self.menubar.addAction(self.main_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Club-Center"))
        self.third_computer_label.setText(_translate("MainWindow", "Место 3"))
        self.fifth_computer_label.setText(_translate("MainWindow", "Место 5"))
        self.second_computer_label.setText(_translate("MainWindow", "Место 2"))
        self.fourth_computer_label.setText(_translate("MainWindow", "Место 4"))
        self.first_computer_label.setText(_translate("MainWindow", "Место 1"))
        self.sixth_computer_label.setText(_translate("MainWindow", "Место 6"))
        self.remove_five_minutes_button.setText(_translate("MainWindow", "Забрать 5 минут"))
        self.start_session_button.setText(_translate("MainWindow", "Начать сеанс"))
        self.add_five_minutes_button.setText(_translate("MainWindow", "Добавить 5 минут"))
        self.remove_one_warning_button.setText(_translate("MainWindow", "Убрать 1 предупреждение"))
        self.send_warning_button.setText(_translate("MainWindow", "Выслать предупреждение"))
        self.block_session_button.setText(_translate("MainWindow", "Заблокировать сеанс"))
        self.remove_reservation_button.setText(_translate("MainWindow", "Убрать выбранную бронь"))
        self.add_reservation_button.setText(_translate("MainWindow", "Добавить бронь"))
        self.back_button.setText(_translate("MainWindow", "Назад"))
        self.label.setText(_translate("MainWindow", "Оставшееся время:"))
        self.label_2.setText(_translate("MainWindow", "2:00:00"))
        self.label_3.setText(_translate("MainWindow", "Кол-во пердупреждений:"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.main_menu.setTitle(_translate("MainWindow", "Главная"))
        self.themes.setTitle(_translate("MainWindow", "Тема"))
        self.action_2.setText(_translate("MainWindow", "Темная"))
        self.white_theme_button.setText(_translate("MainWindow", "Светлая"))
        self.black_theme_button.setText(_translate("MainWindow", "Тёмная"))
